### ISSUE TITLE
Docker Modules

### ISSUE THREAD

**Issue by risphs** [ripe-org/mango-core#1]
When running the Docker image it cannot find the `os-utils` module

Here are the logs:
```console
mango-core-api-1  | - /usr/src/app/src/index.ts
mango-core-api-1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
mango-core-api-1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
mango-core-api-1  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
mango-core-api-1  |     at require (node:internal/modules/cjs/helpers:102:18)
mango-core-api-1  |     at Object.<anonymous> (/usr/src/app/src/index.ts:1:16)
mango-core-api-1  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
mango-core-api-1  |     at Module._compile (/usr/src/app/node_modules/source-map-support/source-map-support.js:568:25)
mango-core-api-1  |     at Module.m._compile (/tmp/ts-node-dev-hook-9395650021934856.js:69:33)
mango-core-api-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
mango-core-api-1  |     at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-9395650021934856.js:114:20)
mango-core-api-1  | [ERROR] 11:46:49 Error: Cannot find module 'os-utils'
```

**Comment by risphs** [comment]
Error has been fixed. It seems to be that it didn't rebuild itself after we changed the import statment.
